# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install amc2moodle
      run: |
        pip install .
    - name: Run amc2moodle
      run: |
        amc2moodle ./test/QCM_wo-tikz.tex -o ./test/QCM_wo-tikz.xml  -k -c amc
        amc2moodle ./test/QCM.tex -o ./test/QCM.xml  -k -c amc
