# This is a basic workflow to help you get started with Actions

name: CI-Ubuntu

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '*' ]
    paths-ignore:         # Don't trigger on files that are updated by the CI
      - README.md
  pull_request:
    branches: [ '*' ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
        # python-version: [3.5]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install the dependences
      run: |
        python -m pip install --upgrade pip
        
        # install ubuntu package
        sudo apt-get install imagemagick
        # move policy file
        sudo mv /etc/ImageMagick-6/policy.xml /etc/ImageMagick-6/policy.xml.off
        sudo apt-get install texlive-latex-recommended texlive-pictures
        # add libtext-unidecode-perl to fix bug in deb package : https://github.com/brucemiller/LaTeXML/issues/1022
        sudo apt-get install libtext-unidecode-perl
        sudo apt-get install latexml
        sudo apt-get install xmlindent
              
    - name: Test latexml
      run: |
        # add --strict flag to be more strict in error catching
        latexml --noparse --nocomment --strict --path=./amc2moodle/amc2moodle --dest=./out.xml  ./amc2moodle/amc2moodle/test/QCM.tex   
    - name: Install amc2moodle
      run: |
        # add -e to have write access for test. TODO : change with temp file
        pip install -e .
    - name: Test amc2moodle
      run: |
        python -m amc2moodle.amc2moodle.test
    - name: Test moodle2amc
      run: |
        python -m amc2moodle.moodle2amc.test        
    - name: Archive test output (no tikz)
      if: ${{ always() }}
      uses: actions/upload-artifact@v1
      with:
        name: test_notikz_${{ matrix.python-version }}
        path: test_notikz.xml    
    - name: Archive test output (tikz)
      if: ${{ always() }}
      uses: actions/upload-artifact@v1
      with:
        name: test_tikz_${{ matrix.python-version }}
        path: test_tikz.xml   
   
        
        

    

